version: "3.8"
services:
    jupyter-server:
        image: dl-jupyter
        init: true
        build:
            context: ./
            dockerfile: jupyter.Dockerfile
        env_file: ./.env
        ports:
            - ${JUPYTER_PORT}:${JUPYTER_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DISABLE_REQUIRE=true
        command:
            [
                "jupyter",
                "notebook",
                "--ip=*",
                "--port=${JUPYTER_PORT}",
                "--allow-root",
                "--notebook-dir=${JUPYTER_DIR}",
                '--NotebookApp.token=${JUPYTER_TOKEN}'
            ]
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: ["gpu"]

    tensorboard:
        image: dl-tensorboard
        build:
            context: ./
            dockerfile: tensorboard.Dockerfile
        ports:
            - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "tensorboard",
                "--logdir=${TENSORBOARD_DIR}",
                "--port=${TENSORBOARD_PORT}",
                "--bind_all",
            ]

    mlflow:
        image: mlflow
        build:
            context: ./
            dockerfile: mlflow.Dockerfile
        ports:
            - ${MLFLOW_PORT}:${MLFLOW_PORT}
        volumes:
            - ${ROOT_DIR}:/jupyter
        command:
            [
                "mlflow",
                "server",
                "--backend-store-uri=${MLFLOW_DIR}",
                "--default-artifact-root=${MLFLOW_DIR}",
                "--port=${MLFLOW_PORT}",
                "--host=0.0.0.0"
            ]
